language: node_js
node_js:
  - "9.10.1"
notifications:
  slack:
    secure: IQDEJBTBckiRxHSfZYB5V/H0P13WRmGLmKKymiEUwNzX/kTy+r0rLU/6uR5k7o47ZaWeSmVjQWP4WZ78vwTaCNOspIHpKzO85iXG6PtlLJypqlAi/wg+I9/3RvM8jm9YjC+rxQ0n4xnJRcln9VnF1GMFBcbaA51dYSJEFz1pi87ecZ7UsIwmCU6onTXVqcRbfKOGp22l7RcIsP7n1hrOgB0vrPxAzVtt2/aT5Uyc3/va3KQk06TYgSfv+NJoSLnk5n1tPdniAkGHSnk7iCc6tkrEQQ3/w70I/QbdO2JTJlwhsgvdazDDHSgaoPDdhGptxqucQYFQarT3Bk9EsN/nOJH8jS7q283yLhHrfldSZbJKaxLHoYYhKZkVdSVEj2y9tSjXAzqCrJBaC6rJMCa6qlzpqQtRbWTkByW8RRi1i4ANQ9GZknaxTvlLM7EqIma7o63eCe5/H6t1Ib5lQFn8vES6UFwI3symeV0XEXrCSmm7HXYDEVV9sTPPsaoBGbHG9aMz10x5DtJZnMjBIO/HuiGC5F1my64UPv4U9zj0qPMU0GTWVntCcIYbHTD91hcB2Ie8AvPLqo0TIT/aT12wPQuoPC4TsA90V5VBpY0tJViwvhLUVBRu7ESYSTTZw3fFdOrgryXeWn0mlXVH9USX90CGpUrPL5Sbo+qYChIdY/s=
